build:
    environment:
        php:
            version: 7.0.20
    tests:
        override:
        -   command: vendor/bin/phpunit
            coverage:
                format: php-clover
                file: build/logs/clover.xml
checks:
    php:
        code_rating: true
        duplication: false
filter:
    excluded_paths:
    - test/