build:
    nodes:
        analysis:
            tests:
                override:
                    - php-scrutinizer-run
        tests-and-coverage:
            requires:
                - node: analysis
            tests:
                override:
                    - command: vendor/bin/phpunit
                      coverage:
                          format: clover
                          file: build/logs/clover.xml
    environment:
        php:
            version: 7.2
filter:
    excluded_paths:
        - test/
        - examples/
    dependency_paths:
        - vendor/
checks:
    php:
        code_rating: true
        duplication: false
